# Generated by Django 4.2.4 on 2023-08-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('checking', 'Cuenta Corriente'), ('savings', 'Caja de Ahorro'), ('credit', 'Tarjeta de Crédito'), ('other', 'Otra')], default='other', max_length=20),
        ),
    ]
